### ISSUE TITLE
run_command is not working correctly.(bungee module)

### ISSUE THREAD

**Issue by portlek** [MiniDigger/MiniMessage#13]
`<green><click:run_command:tournament accept>Accept <red><click:run_command:tournament deny>Deny`
![image](https://user-images.githubusercontent.com/12835420/81456796-714cb680-919c-11ea-91a8-acf43d33cefc.png)
after clicking the accept or deny, the result is just sending message although it should run the command.

**Comment by portlek** [comment]
`ClickEvent(action=RUN_COMMAND, value=tournament accept)`
click event object returning that but...

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/81457794-3cdaf980-91a0-11ea-9fce-052bbe7c5964.png)
![image](https://user-images.githubusercontent.com/12835420/81457799-3fd5ea00-91a0-11ea-84f2-b6d4be1ea062.png)
the basic base component is not working too.

So the issue is not about the library.

**Comment by MiniDigger** [comment]
you have to enter a slash. run_command is actually more like enter_in_chat

**Comment by portlek** [comment]
Yes i found and fixed.

**Comment by portlek** [comment]
![image](https://user-images.githubusercontent.com/12835420/81472954-1353b980-9204-11ea-9f28-ee971f67b835.png)
you should show that using method in the readme too.

**Comment by MiniDigger** [comment]
done, thanks for pointing it out
