### ISSUE TITLE
<reset> doesn't work

### ISSUE THREAD

**Issue by KingAlterIV** [MiniDigger/MiniMessage#16]
As the title says, `<reset>` doesn't work with the example taken from the Spigot resource page.
![Image of example](https://i.imgur.com/YERElky.png)
![Image of `<reset>`](https://i.imgur.com/ncgBcZI.png)

**Comment by MiniDigger** [comment]
Mmmmmh, not really sure how reset would work.
in your case, you prolly want:
`You should get a <blue><lang:block.minecraft.diamond_block></blue>!`.  
however, I do see the value in a reset tag.

Would it just remove all decoration and color from the stack?
`<blue>Blue<bold>BlueBold<yellow>YellowBold<underlined>YellowUnderlined<reset>Nothing`?

**Comment by KingAlterIV** [comment]
Yes, that would be the intended effect for `<reset>`. It would basically reset the message back to normal, so no hover, click, anything wouldn't affect it until you declare the message again.
`<hover:show_text:"<yellow>Hovering over me will show something"><blue>Hey I'm a blue text!<reset>I have no hover over me`
